version: "3.7"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=youtube
    ports:
      - "127.0.0.1:21003:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "127.0.0.1:8001:8000"
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db
