# Generated by Django 3.0.4 on 2022-07-10 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100, unique=True)),
                ('page', models.IntegerField(default=0)),
                ('etag', models.CharField(max_length=50)),
                ('next_page_key', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'query_data',
            },
        ),
        migrations.CreateModel(
            name='YoutubeFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, unique=True)),
                ('video_title', models.CharField(max_length=500)),
                ('publish_date', models.DateTimeField()),
                ('video_desc', models.CharField(max_length=500)),
                ('thumbnail', models.CharField(max_length=100)),
                ('video_etag', models.CharField(max_length=50)),
                ('query', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.QueryData')),
            ],
            options={
                'db_table': 'youtube_feed',
            },
        ),
        migrations.CreateModel(
            name='QueryFeedMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField()),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.YoutubeFeed')),
                ('query', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.QueryData')),
            ],
            options={
                'db_table': 'query_feed_mapper',
            },
        ),
    ]
