# Generated by Django 3.0.4 on 2022-07-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubefeed',
            name='video_id',
            field=models.CharField(max_length=100),
        ),
    ]
